id: PE7818BB3
initial_creation_type: ocr
source_metadata:
  volumes:
    a3cc55bfdf0743298b56acaca8914eee:
      base_file: v055.txt
      image_group_id: I1PD95900
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་འབུམ་པ་དང་། ཉི་ཁྲི་ལྔ་སྟོང་པ་དང་། ཁྲི་བརྒྱད་སྟོང་པའི་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1470
      volume_number: 55
